# Generated by Django 5.2.11 on 2026-02-13 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('office_staff', 'Office Staff'), ('conductor', 'Conductor'), ('driver', 'Driver')], default='office_staff', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('all', 'All'), ('cargo', 'Cargo'), ('passenger', 'Passenger')], help_text='Only for office_staff. Admin/conductor/driver = null.', max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('device_bound_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='api.office')),
            ],
            options={
                'verbose_name_plural': 'buses',
                'db_table': 'buses',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.office'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('passenger_base_price', models.PositiveIntegerField()),
                ('cargo_small_price', models.PositiveIntegerField()),
                ('cargo_medium_price', models.PositiveIntegerField()),
                ('cargo_large_price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='api.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_trips', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='api.office')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='api.office')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('accepted', models.PositiveIntegerField(default=0)),
                ('quarantined', models.PositiveIntegerField(default=0)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to='api.trip')),
            ],
            options={
                'db_table': 'sync_log',
            },
        ),
        migrations.CreateModel(
            name='QuarantinedSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_data', models.JSONField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantined_syncs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quarantines', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantined_syncs', to='api.trip')),
            ],
            options={
                'db_table': 'quarantined_syncs',
            },
        ),
        migrations.CreateModel(
            name='PassengerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_number', models.CharField(max_length=20)),
                ('passenger_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('prepaid', 'Prepaid')], default='cash', max_length=20)),
                ('seat_number', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_passenger_tickets', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_tickets', to='api.trip')),
            ],
            options={
                'db_table': 'passenger_tickets',
            },
        ),
        migrations.CreateModel(
            name='CargoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_number', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('cargo_tier', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('payment_source', models.CharField(choices=[('prepaid', 'Prepaid'), ('pay_on_delivery', 'Pay on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('refused', 'Refused'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('status_override_reason', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cargo_tickets', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_deliveries', to=settings.AUTH_USER_MODEL)),
                ('status_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_overrides', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_tickets', to='api.trip')),
            ],
            options={
                'db_table': 'cargo_tickets',
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.trip')),
            ],
            options={
                'db_table': 'trip_expenses',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('override', 'Override')], max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['-created_at', 'user'], name='idx_audit_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_price', models.PositiveIntegerField()),
                ('cargo_small_price', models.PositiveIntegerField()),
                ('cargo_medium_price', models.PositiveIntegerField()),
                ('cargo_large_price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_to', to='api.office')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_from', to='api.office')),
            ],
            options={
                'db_table': 'pricing_config',
                'constraints': [models.UniqueConstraint(fields=('origin_office', 'destination_office', 'effective_from'), name='uq_pricing_route_date')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['origin_office', '-departure_datetime'], name='idx_trips_office_date'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(condition=models.Q(('status__in', ['scheduled', 'in_progress'])), fields=['conductor', 'status'], name='idx_trips_conductor_status'),
        ),
        migrations.AddIndex(
            model_name='quarantinedsync',
            index=models.Index(fields=['status', '-created_at'], name='idx_quarantine_status'),
        ),
        migrations.AddIndex(
            model_name='passengerticket',
            index=models.Index(fields=['trip'], name='idx_passenger_trip'),
        ),
        migrations.AddConstraint(
            model_name='passengerticket',
            constraint=models.UniqueConstraint(fields=('trip', 'ticket_number'), name='uq_passenger_trip_ticket'),
        ),
        migrations.AddIndex(
            model_name='cargoticket',
            index=models.Index(fields=['trip'], name='idx_cargo_trip'),
        ),
        migrations.AddIndex(
            model_name='cargoticket',
            index=models.Index(condition=models.Q(('status__in', ['paid', 'refused', 'cancelled']), _negated=True), fields=['trip', 'status'], name='idx_cargo_unpaid'),
        ),
        migrations.AddConstraint(
            model_name='cargoticket',
            constraint=models.UniqueConstraint(fields=('trip', 'ticket_number'), name='uq_cargo_trip_ticket'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip'], name='idx_expense_trip'),
        ),
    ]
