# Generated by Django 5.2.11 on 2026-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_money_column_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passengerticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure_datetime']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_user_time',
        ),
        migrations.RemoveIndex(
            model_name='cargoticket',
            name='idx_cargo_trip_tier',
        ),
        migrations.RemoveIndex(
            model_name='passengerticket',
            name='idx_ticket_trip_status',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='idx_trip_route_date',
        ),
        migrations.AddField(
            model_name='passengerticket',
            name='alighting_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passengerticket',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
