# Generated by Django 5.1.5 on 2026-03-02 14:00

from django.db import migrations


def soft_delete_legacy_roles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    
    # Isolate out any users matching the unspecced 'driver' role or 'passenger' dept
    # and soft-delete them instead of automatically promoting them.
    # We set department_review_needed=True to flag them for admins, though we'll just
    # use the existing fields to keep it simple.
    
    legacy_users = User.objects.filter(role='driver') | User.objects.filter(department='passenger')
    
    affected_count = legacy_users.count()
    if affected_count > 0:
        print(f"\n[Security Migration] Found {affected_count} users with legacy role='driver' or department='passenger'.")
        print("[Security Migration] Soft-deactivating these users for manual admin review to prevent privilege escalation...")
        
        legacy_users.update(is_active=False)
        
        print("[Security Migration] Done.")


def reverse_soft_delete(apps, schema_editor):
    # Reversing this would mean re-activating them, but since we don't know who
    # was *already* inactive vs who we just deactivated, this is a no-op to be safe.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cargoticket_options_and_more'),
    ]

    operations = [
        migrations.RunPython(soft_delete_legacy_roles, reverse_code=reverse_soft_delete),
    ]
