# Generated by Django 5.2.11 on 2026-03-14 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_synclog_key_varchar100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('cargo', 'Cargo')], help_text='Only for office_staff. Admin/conductor = null.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office_staff', 'Office Staff'), ('conductor', 'Conductor')], default='office_staff', max_length=20),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_passenger_cash', models.PositiveIntegerField(default=0)),
                ('expected_cargo_cash', models.PositiveIntegerField(default=0)),
                ('expected_total_cash', models.PositiveIntegerField(default=0)),
                ('agency_presale_total', models.PositiveIntegerField(default=0)),
                ('outstanding_cargo_delivery', models.PositiveIntegerField(default=0)),
                ('expenses_to_reimburse', models.PositiveIntegerField(default=0)),
                ('net_cash_expected', models.IntegerField(default=0)),
                ('actual_cash_received', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_expenses_reimbursed', models.PositiveIntegerField(default=0)),
                ('discrepancy_amount', models.IntegerField(blank=True, help_text='= (actual_cash_received - actual_expenses_reimbursed) - net_cash_expected. In v1 this combines cash variance and reimbursement variance into one net reconciliation difference.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('settled', 'Settled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_settlements', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(help_text='Destination office where cash is handed over.', on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='api.office')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_settlements', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='api.trip')),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['office', 'status'], name='idx_settlement_office_status'), models.Index(fields=['conductor', '-created_at'], name='idx_settlement_conductor_date')],
            },
        ),
    ]
