# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tripexpense_synced_at_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='category',
            field=models.CharField(
                choices=[
                    ('fuel', 'Fuel'),
                    ('food', 'Food'),
                    ('maintenance', 'Maintenance'),
                    ('tolls', 'Tolls'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20,
            ),
        ),
    ]
