# Generated by Django 5.2.12 on 2026-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tripexpense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseMirrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=16)),
                ('op_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_updated_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'firebase_mirror_events',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_fbmirror_status_retry'), models.Index(fields=['entity_type', 'entity_id'], name='idx_fbmirror_entity')],
            },
        ),
    ]
